### ISSUE TITLE
Unable to test this extension..

### ISSUE THREAD

**Issue by DynamoDesignDevelopment** [myflashlab/UDID-ANE#1]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
Animate publish testing

## Problem Description ##
import com.myflashlab.air.extensions.udid.UDID;
UDID.init();
if(UDID.OS == UDID.ANDROID) trace(UDID.androidId);
else if(UDID.OS == UDID.IOS) trace(UDID.vendorId);

## Steps to Reproduce ##
Just testing straight up with your sample code. all required ane's are imported.

Output Error:

ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.udid::UDID()
	at com.myflashlab.air.extensions.udid::UDID$/init()
	at _555_fla::MainTimeline/frame1()[_555_fla.MainTimeline::frame1:6]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()

**Comment by DynamoDesignDevelopment** [comment]
@myflashlab

**Comment by myflashlab** [comment]
This error message means that the ANE is not implemented correctly OR maybe you are running on the simulator. Maybe watching these videos might be helpful to you:

https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by DynamoDesignDevelopment** [comment]
@myflashlab It's implement properly like every other I have. I have multiple extensions that operate in the air debug launcher, I assume this wasn't coded to be able to test it?

**Comment by myflashlab** [comment]
The available demo ANE in our GitHub repository works fine. Please post your manifest while you are double checking the implementation. We have seen these errors before and  they always happen when the ANE is not correctly implemented OR if you are testing on a simulator and not a real device.

**Comment by deesnay** [comment]
I find this extension very useful, but I haven't been able to implement it in a FlashBuilder project so far.
The UDID ANE itself gets installed fine, and works, but only some of the UDID class properties work as expected. Others (such as androidId) cause a runtime error (debugging on an Android device via USB).
```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.myflashlab.air.extensions.udid::UDID$/get androidId()
```
I assume this is because the dependencies are missing...?
But if I add the dependencies to the project, these other ANEs are marked as invalid, and I get errors (inside FlashBuilder) such as:
"extension.xml file missing", or "error in opening zip file".
I've checked your video Tutorials. Can you help me?

**Comment by myflashlab** [comment]
The required dependencies are mentioned here: https://github.com/myflashlab/UDID-ANE#air-xml-manifest. You should try to add them to your project. Also make sure you are compiling on a real device not the emulator.

You said you are seeing this error:
```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.myflashlab.air.extensions.udid::UDID$/get androidId()
```
Have you called ```UDID.init();``` before calling ```UDID.androidId```?

**Comment by deesnay** [comment]
Thanks for your help.
I made some progress inbetween.
I realized that I had not downloaded the dependency ANE files correctly (I did download files with an .ane extension, but they were XML files, and not the actual ANEs).
However, I still had a problem with the androidSupport ANE (lite or full), that caused errors on compiling.
I noticed that removing this specific library from the project allowed me to compile correctly, and still get the `androidId` I needed.
I'll proceed to purchasing the ANE.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
