### ISSUE TITLE
iOS always limited ad tracking

### ISSUE THREAD

**Issue by OceanBreezeGames** [myflashlab/UDID-ANE#4]
No matter if I have limited ad tracking toggled on/off in the privacy settings of my device the result function for UDID.retriveAdId always returns true for the limited ad tracking. 

Any ideas why?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
